services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - data_pg:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - app
    
  redis:
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - app
  
  celery:
    build: ./back
    volumes:
      - ./back/app:/code
    networks:
      - app
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: celery -A config worker -l info

volumes:
  data_pg:
    driver: local


networks:
  app:
    driver: bridge